[2025-05-06 22:16:09] ERROR - Test Failed: contactUsForm - com.JodaynDemo.tests.TC6_ContactUs
[2025-05-06 22:16:09] ERROR - Error: java.lang.AssertionError: Verify success message 'Success! Your details have been submitted successfully.' is visible expected [Success! Your details have been submitted successfully..] but found [Success! Your details have been submitted successfully.]
[2025-05-06 22:16:09] ERROR - org.testng.Assert.fail(Assert.java:111)
[2025-05-06 22:16:09] ERROR - org.testng.Assert.failNotEquals(Assert.java:1590)
[2025-05-06 22:16:09] ERROR - org.testng.Assert.assertEqualsImpl(Assert.java:150)
[2025-05-06 22:16:09] ERROR - org.testng.Assert.assertEquals(Assert.java:132)
[2025-05-06 22:16:09] ERROR - org.testng.Assert.assertEquals(Assert.java:656)
[2025-05-06 22:16:09] ERROR - com.JodaynDemo.tests.TC6_ContactUs.verifySuccessMessageSuccessYourDetailsHaveBeenSubmittedSuccessfullyIsVisible(TC6_ContactUs.java:52)
[2025-05-06 22:16:09] ERROR - com.JodaynDemo.tests.TC6_ContactUs.contactUsForm(TC6_ContactUs.java:31)
[2025-05-06 22:16:09] ERROR - java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2025-05-06 22:16:09] ERROR - java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2025-05-06 22:16:09] ERROR - org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
[2025-05-06 22:16:09] ERROR - org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
[2025-05-06 22:16:09] ERROR - org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
[2025-05-06 22:16:09] ERROR - org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
[2025-05-06 22:16:09] ERROR - org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
[2025-05-06 22:16:09] ERROR - org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
[2025-05-06 22:16:09] ERROR - org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
[2025-05-06 22:16:09] ERROR - org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
[2025-05-06 22:16:09] ERROR - java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[2025-05-06 22:16:09] ERROR - java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[2025-05-06 22:16:09] ERROR - org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
[2025-05-06 22:16:09] ERROR - java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2025-05-06 22:16:09] ERROR - java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2025-05-06 22:16:09] ERROR - java.base/java.lang.Thread.run(Thread.java:1583)
